### ISSUE TITLE
Content Klassen sollen keinen doppelten Code enthalten.

### ISSUE THREAD

**Issue by derUli** [zirafa/bootstrap-grid-only#5]
z.B. den Type als Klassenvariable,
Basis-Inhaltstypen extenden und die Save Load usw. Funktionen overriden, Funktion aus Parent Klasse aufrufen und nicht darin enthaltene Klassen danach per update setzen.

**Comment by zirafa** [comment]
Screenshot or P.R.? Does the problem exist upstream in Bootstrap itself?

**Comment by derUli** [comment]
Sorry. I posted this accidently to  a wrong repository.
